org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.1.43
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=luncheon
mod_name=Luncheon
mod_license=MIT
mod_version=1.1.0
mod_group_id=net.vercte
mod_authors=Vercte
mod_description=I hope you're prepared for an unforgettable luncheon!

jei_version = 15.20.0.106
emi_version = 1.1.19+1.20.1

create_version = 6.0.7
ponder_version = 1.0.80
flywheel_version = 1.0.4
registrate_version = MC1.20-1.3.3